version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ~/db:/var/db
    restart: always
    container_name: theBestMongo
  node:
    image: node:6.10.3
    volumes:
      - ${PWD}:/var/local
    ports:
      - 80:3000
    links:
      - mongo:database
    restart: always
    container_name: theBestNode
    command: node /var/local/server.js
    env_file:
      - ./.env

